export { Header } from './Header';
export { Hero } from './Hero';
export { About } from './About';
export { Stats } from './Stats';
export { GameplayFeatures } from './GameplayFeatures';
export { Trailer } from './Trailer';
export { Gallery } from './Gallery';
export { Footer } from './Footer';
export { LoadingScreen } from './LoadingScreen';
